---
output:
  bookdown::pdf_document2:
    toc : no
    keep_tex: no
    number_sections: yes
---

<!-- Note this section is Required -->

\doublespacing

The following individuals certify that they have read, and recommend to the Faculty of Graduate
and Postdoctoral Studies for acceptance, the dissertation entitled:

\vspace{5mm}


\noindent\underline{\makebox[6in][l]{Countergradient variation in lodgepole pine flowering phenology}}  
\vspace{2mm}

submitted by \underline{Carolyn Susannah Tysor} in partial fulfillment of the requirements for

the degree of \noindent\underline{\makebox[5in][l]{Master of Science}}  

in \noindent\underline{\makebox[5.8in][l]{Forestry}}

\vspace{5mm}

**Examining Committee:**

\noindent\underline{\makebox[6in][l]{Sally Aitken, Professor, Department of Forest and Conservation Sciences, UBC}}  
Supervisor

\noindent\underline{\makebox[6in][l]{Elizabeth Wolkovich, Associate Professor and Canada Research Chair in Temporal Ecology, Department of Forest and Conservation Sciences, UBC}}  
Supervisory Committee Member

\noindent\underline{\makebox[6in][l]{Michael Whitlock, Professor, Department of Zoology, UBC}}  
Supervisory Committee Member

\noindent\underline{\makebox[6in][l]{Name of University Examiner}}  
University Examiner

\noindent\underline{\makebox[6in][l]{Name of University Examiner}}  
University Examiner

\noindent\underline{\makebox[6in][l]{Name of External Examiner}}  
External Examiner

<!-- Committee members that did not attend the defence -->
**Additional Supervisory Committee Members:**

\noindent\underline{\makebox[6in][l]{Name of your Committee Member}}  
Supervisory Committee Member
