---
output:
  bookdown::pdf_book:
    toc : no
    keep_tex: no
    number_sections: yes
---

<!-- This is mandatory! -->

This project takes advantage of existing lodgepole pine phenology data collected over a decade and a half by government and industry workers in seed orchards in British Columbia. The data was provided to me by Rita Wagner (Prince George Tree Improvement Station), Chris Walsh (Kalamalka seed orchards), and Joe Webber (Glynn Road Research Station). Rob Johnstone assisted in the transcription of handwritten datasheets and I compiled, cleaned, and harmonized the phenology data into a usable data set.

I was responsible for developing the research questions, designing and performing the modeling, analyzing the results, and writing the thesis under the supervision of Dr. Sally Aitken. My entire supervisory committee provided input into modelling and analysis decisions and feedback on interpretation of results as well as detailed edits and comments on the thesis itself.

Sarah Bisbing and Conor Phelan provided the shapefile for the *Pinus contorta* ssp. *latifolia* range map in Figure \@ref(fig:rangemap).

The generative AI tool ChatGPT was used to:

1) create custom legends for several figures and adjust figure aesthetics,
2) help debug analysis code, and 
3) create a reverse outline of an earlier draft of this thesis which I used (without generative AI) to edit the structure of the document.