---
output:
  bookdown::pdf_book:
    toc : no
    keep_tex: no
    number_sections: yes
---

<!-- This section is mandatory! -->

This study uses a novel thermal time model to estimate forcing requirements for both receptivity and pollen shed in *Pinus contorta* ssp. *latifolia* (lodgepole pine), quantifies countergradient variation and within-population variation in flowering, and predicts significant advancements in flowering under climate change. 
Estimates are based on a model fit using my assembly of the most comprehensive data set of lodgepole pine flowering available to date, spanning 149 provenances grown at 7 sites and observed over 16 years.
Unlike many phenology models that rely on day of year, which limits their applicability, the model developed here can be used across different locations and years. 

This model offers a powerful tool for predicting flowering timing across space and time, deepening insights into gene flow, adaptation, and climate change impacts on lodgepole pine.
Its adaptability will allow flowering predictions across large regions to be assessed for overlap, with potential integration into wind models to evaluate pollen-mediated population connectivity.
Given flowering's critical role in both fecundity and gene flow, these predictions will be valuable for investigating eco-evolutionary dynamics, particularly the influence of phenology on lodgepole pine range limits [@Chuine2001b]. 
Additionally, phenology model outputs could be incorporated into larger process-based models to explore fitness consequences of plasticity and adaptation under past and future climates [@gauzere2020; @Duputie2015].

The large within-population variation in flowering and modest countergradient variation associated with provenance mean annual temperature (MAT) that I found have important implications for gene flow and adaptation. 
Temperature-controlled flowering does restrict gene flow to populations from more similar climates, but both the within-population and countergradient variation act to increase gene flow among populations from more different climates. 
Phenology, however, is not the only factor controlling gene flow; studies that consider wind dispersal of pollen are necessary to understand the impacts of pollen mediated gene flow in lodgepole pine and how it will affect adaptation under climate change [@kremer2012]. The direction of pollen dispersal influences evolution along the gradient [@Soularue2014], but modelling pollen dispersal over large distances is a difficult problem. It could be simplified by using pollination phenology to rule out gene flow between populations with unmatched flowering phenology. 

Advances in flowering phenology of several weeks are anticipated for lodgepole pine under climate change. While the limited analyses here suggest advancement will not have a large impact on gene flow, further investigation is warranted using more sites or even considering the full range. Other climate change impacts could be incorporated as well. Importantly, gene flow could be impacted by extensive logging, range shifts likely under climate change [@mackenzie2021], or other disruptions due to climate change like increased fire and bark beetle outbreaks [@Sambaraju2012; @parisien2023]. Gene flow may simply be lost from many populations because they are gone, temporarily or permanently.

Data collected in seed orchards is invaluable for research, as demonstrated in this study. However, its use is limited by inconsistent collection methods, varied recording formats, and its fragmentation across many sites. The flowering phenology dataset used here, sourced from both government and private entities, required substantial effort to obtain, standardize, and clean before analysis. Consolidating, standardizing, and publishing similar data from seed orchards would maximize the return on investment, making it more accessible for future research and broader applications.

Although the model currently uses MAT to represent provenance, MAT may not capture the true drivers of population differences — a hypothesis that could be tested by comparing phenology at sites with contrasting MAT but similar spring warmups. 
MAT's performance as a proxy variable could be tested by ground truthing phenology at site pairs like Border and Trench, which have very different MATs due to winter differences but very similar spring warmups. 
When provenances with very different MATs have very similar spring warmups, their forcing requirements will be different according to the model here. 
This means divergence in flowering time and reduced gene flow potential between populations that are relatively similar in climate. 
Climate variables other than MAT may better represent provenance variation and should be investigated.

The thermal time model presented here offers a straightforward yet powerful approach for predicting lodgepole pine flowering and provides a solid foundation for extension across the species range.
To expand its use to more southerly regions of the range or to enhance climate change projections, the model could be tested and calibrated with data from additional southern provenances.
This model was built using observational data, but experiments may provide better forcing estimates, clarify whether and how to include photoperiod and chilling effects, and quantify forcing thresholds [@hanninen2019; @Chuine2001]. 
Additionally, incorporating both start and end events into a multi-stage model could yield more precise predictions, especially for end events.

This study’s flowering phenology model and data set for lodgepole pine offer a foundation for future research into climate-driven phenological shifts, gene flow, and adaptation. Building on this work could reveal new insights into how phenology influences ecological and evolutionary dynamics under climate change across lodgepole pine’s range.